# EE460J Data Science Lab (Spring 2022)

### Author: Sunny Sanyal
This notebook reviews some of the basics of pytorch to be used in this course. This is just a warm before you jump right into the lab sessions. Following resources have been used in preparation of this tutorial:

*  Python tutorial CS224N: Natural Language Processing with Deep Learning 

## Installation of cudatoolkit and creating environment

1. Download cudatoolkit from __[here](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local)__ 


#### Creating environment on anaconda prompt


<code>conda create --name dl_env python=3.8.5
conda activate dl_env
conda install -c conda-forge tensorboardx tqdm python-louvain numpy pandas matplotlib 
conda install -c anaconda scikit-learn scipy pandas
conda install pytorch torchvision cudatoolkit=11.3 -c pytorch
</code>


##### Adding the environment to your jupyter notebook


<code>pip install --user ipykernel
python -m ipykernel install --user --name=dl_env
jupyter notebook 
</code>

## Checking if CUDA is available 

also if torch isn't running look __[here](https://stackoverflow.com/questions/69958526/oserror-winerror-127-the-specified-procedure-could-not-be-found)__ 

In [1]:
import torch
import torch.nn as nn
import pprint
pp = pprint.PrettyPrinter()
torch.cuda.is_available()

True

## Tensors

Tensors are the most basic building blocks in PyTorch. Tensors are similar to matrices, but the have extra properties and they can represent higher dimensions. For example, an square image with 256 pixels in both sides can be represented by a 3x256x256 tensor, where the first 3 dimensions represent the color channels, red, green and blue.

### Tensor Initialization

There are several ways to instantiate tensors in PyTorch, which we will go through next.

#### From a Python list

In [19]:
data = [
        [0,1],
        [2,3],
        [4,5]
        ]
nrow=len(data)
ncol= len(data[0])
print(nrow)
print(ncol)
#print(type(data))
x_python = torch.tensor(data)

# Print the tensor
x_python

3
2


tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [20]:
# We are using the dtype to create a tensor of particular type
x_float = torch.tensor(data, dtype=torch.float)
x_float

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [21]:
# We are using the dtype to create a tensor of particular type
x_bool = torch.tensor(data, dtype=torch.bool)
x_bool

tensor([[False,  True],
        [ True,  True],
        [ True,  True]])

In [22]:
x_python.float()

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [23]:
# `torch.Tensor` defaults to float
# Same as torch.FloatTensor(data)
x = torch.Tensor(data) 
x

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

#### From a Numpy Array

In [25]:
import numpy as np

# Initialize a tensor from a NumPy array
ndarray = np.array(data)
x_numpy = torch.from_numpy(ndarray)

# Print the tensor
x_numpy

tensor([[0, 1],
        [2, 3],
        [4, 5]], dtype=torch.int32)

#### From a Tensor

We can also initialize a tensor from another tensor, using the following methods:

* torch.ones_like(old_tensor): Initializes a tensor of 1s.
* torch.zeros_like(old_tensor): Initializes a tensor of 0s.
* torch.rand_like(old_tensor): Initializes a tensor where all the elements are sampled from a uniform distribution between 0 and 1.
* torch.randn_like(old_tensor): Initializes a tensor where all the elements are sampled from a normal distribution.

In [27]:
# Initialize a base tensor
x = torch.tensor([[1., 2.], [3., 4.]])
x

tensor([[1., 2.],
        [3., 4.]])

In [28]:
# Initialize a tensor of 0s
x_zeros = torch.zeros_like(x)

x_zeros

tensor([[0., 0.],
        [0., 0.]])

In [29]:
# Initialize a tensor of 1s
x_ones = torch.ones_like(x)

x_ones

tensor([[1., 1.],
        [1., 1.]])

In [30]:
# Initialize a tensor where each element is sampled from a uniform distribution
# between 0 and 1

x_rand = torch.rand_like(x)

x_rand

tensor([[0.5777, 0.4022],
        [0.5218, 0.9841]])

In [31]:
# Initialize a tensor where each element is sampled from a normal distribution
x_randn = torch.randn_like(x)
x_randn

tensor([[-0.3616,  1.1374],
        [-0.6897,  2.2172]])

#### Generating Tensors specifying a Shape

* torch.zeros()
* torch.ones()
* torch.rand()
* torch.randn()

In [32]:
# Initialize a 2x3x2 tensor

shape = (4, 2, 2)
x_zeros = torch.zeros(shape)

x_zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

#### With torch.arange()

We can also create a tensor with torch.arange(end), which returns a 1-D tensor with elements ranging from 0 to end-1. We can use the optional start and step parameters to create tensors with different ranges.

In [33]:
# Create a tensor with values 1D

x= torch.arange(10)

x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Tensor Properties

Tensors have a few properties that are important for us to cover. These are namely shape, and the device properties.

In [ ]:
#### Data type
The dtype property lets us see the data type of a tensor.

In [34]:
# Initialize a 3x2 tensor, with 3 rows and 2 columns
x = torch.Tensor([[1, 2], [3, 4], [5, 6]])
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [35]:
# Print out its shape
# Same as x.size()
x.shape 

torch.Size([3, 2])

In [36]:
# Print out the number of elements in a particular dimension
# 0th dimension corresponds to the rows
x.shape[0] 

3

In [37]:
# 1st dimension corresponds to the columns
x.shape[1]

2

In [38]:
# We can change the shape of a tensor with the view( method
# Example use of view()
# x_view shares the same memory as x, so changing one changes the other
x_view = x.view(3, 2)
x_view

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [39]:
x_view1 = x.view(2, 3)
x_view1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [40]:
x_view = x.view(-1, 3)
x_view

tensor([[1., 2., 3.],
        [4., 5., 6.]])

We can also use torch.reshape() method for a similar purpose. There is a subtle difference between reshape() and view(): view() requires the data to be stored contiguously in the memory. You can refer to this StackOverflow answer for more information. In simple terms, contiguous means that the way our data is laid out in the memory is the same as the way we would read elements from it. This happens because some methods, such as transpose() and view(), do not actually change how our data is stored in the memory. They just change the meta information about out tensor, so that when we use it we will see the elements in the order we expect.

reshape() calls view() internally if the data is stored contiguously, if not, it returns a copy. The difference here isn't too important for basic tensors, but if you perform operations that make the underlying storage of the data non-contiguous (such as taking a transpose), you will have issues using view(). If you would like to match the way your tensor is stored in the memory to how it is used, you can use the contiguous() method.

In [41]:
# Change the shape of x to be 3x2
# x_reshaped could be a reference to or copy of x
x_reshaped = torch.reshape(x, (2, 3))
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [43]:
# Initialize a 5x2 tensor with 5 rows and 2 columns

x =torch.arange(10).reshape(5,2)

x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [44]:
y= torch.arange(10)
x =torch.reshape(y, (5,2))

x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [52]:
# Add a new dimension of size 1 at the 1st dimension
x = x.unsqueeze(1)

x.shape

torch.Size([5, 1, 1, 1, 1, 1, 2])

In [53]:
# Squeeze the dimensions of x by getting rid of all the dimensions with 1 element
x = x.squeeze()

x.shape

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [47]:
# Squeeze the dimensions of x by getting rid of all the dimensions with 1 element
x = x.squeeze()
x.shape

torch.Size([5, 2])

In [54]:
# Get the number of elements in tensor.
x.numel()

10

### Device

Device property tells PyTorch where to store our tensor. Where a tensor is stored determines which device, GPU or CPU, would be handling the computations involving it. We can find the device of a tensor with the device property.

In [2]:
# Initialize an example tensor
x = torch.Tensor([[1, 2], [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# Get the device of the tensor
x.device

device(type='cpu')

In [4]:
# We can move a tensor from one device to another with the method to(device).

# Check if a GPU is available, if so, move the tensor to the GPU
if torch.cuda.is_available():
  x.to('cuda') 

### Tensor Indexing

In PyTorch we can index tensors, similar to NumPy.

In [7]:
x = torch.Tensor([
                  [[1, 2], [3, 4]],
                  [[5, 6], [7, 8]], 
                  [[9, 10], [11, 12]] 
                 ])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [6]:
x.shape

torch.Size([3, 2, 2])

In [8]:
# Access the 0th element, which is the first row
x[0] # Equivalent to x[0, :]

tensor([[1., 2.],
        [3., 4.]])

In [10]:
# We can also access arbitrary elements in each dimension.

# let's access the 0th and 1st elements
i = torch.tensor([0,1])
x[i]

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [11]:
# Get the top left element of each element in our tensor
x[:, 0, 0]

tensor([1., 5., 9.])

In [12]:
x[0,0,0]

tensor(1.)

In [13]:
x[0,0,0].item()

1.0

#### Tensor Operations

PyTorch operations are very similar to those of NumPy. We can work with both scalars and other tensors.

In [15]:
x =  torch.ones((3,2,2))

x

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [16]:
# Perform elementwise addition
# Use - for subtraction
x + 2

tensor([[[3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.]]])

In [17]:
# Perform elementwise multiplication
# Use / for division
x * 2

tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])

In [19]:
a = torch.ones((4,3))

a * 6

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

In [21]:
# Create a 1D tensor of 2s
b = torch.ones(3) * 2
b

tensor([2., 2., 2.])

In [22]:
# Divide a by b
a / b

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [23]:
a/2

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [24]:
# We can use tensor.matmul(other_tensor) for matrix multiplication and tensor.T for transpose. Matrix multiplication can also be performed with @.
# Alternative to a.matmul(b)
# a @ b.T returns the same result since b is 1D tensor and the 2nd dimension
# is inferred
a @ b 

tensor([6., 6., 6., 6.])

In [25]:
pp.pprint(a.shape)
pp.pprint(a.T.shape)

torch.Size([4, 3])
torch.Size([3, 4])


We can take the mean and standard deviation along a certain dimension with the methods mean(dim) and std(dim). That is, if we want to get the mean 3x2 matrix in a 4x3x2 matrix, we would set the dim to be 0. We can call these methods with no parameter to get the mean and standard deviation for the whole tensor. To use mean and std our tensor should be a floating point type.

In [31]:
m = torch.tensor(
    [
     [1., 1.],
     [2., 2.],
     [3., 3.],
     [4., 4.]
    ]
)


pp.pprint('Mean: {}'.format(m.mean()))
pp.pprint("Mean in the 0th dimension: {}".format(m.mean(0)))
pp.pprint("Mean in the 1st dimension: {}".format(m.mean(1)))

'Mean: 2.5'
'Mean in the 0th dimension: tensor([2.5000, 2.5000])'
'Mean in the 1st dimension: tensor([1., 2., 3., 4.])'


In [34]:
# We can concatenate tensors using torch.cat.
# concatenate in deomension 0 rows
a_cat0 = torch.cat([a, a], dim=0)
print("Initial shape: {}".format(a.shape))
print("Initial shape: {}".format(a_cat0.shape))
a_cat0

Initial shape: torch.Size([4, 3])
Initial shape: torch.Size([8, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [35]:
# concatenate in deomension 1 columns
a_cat1 = torch.cat([a, a], dim=1)
print("Initial shape: {}".format(a.shape))
print("Initial shape: {}".format(a_cat1.shape))
a_cat1

Initial shape: torch.Size([4, 3])
Initial shape: torch.Size([4, 6])


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

### Autograd

PyTorch and other machine learning libraries are known for their automatic differantiation feature. That is, given that we have defined the set of operations that need to be performed, the framework itself can figure out how to compute the gradients. We can call the backward() method to ask PyTorch to calculate the gradiends, which are then stored in the grad attribute.

In [41]:
# Create an example tensor
# requires_grad parameter tells PyTorch to store gradients
x = torch.tensor([2.], requires_grad=True)
# no grad since it's a scalar
print(x.grad)

None


In [44]:
# Calculating the gradient of y with respect to x
y = x * x * 3 #3x^2
y.backward()
print(x.grad) # d(y)/d(x) = d(3x^2)/d(x) = 6x = 12

tensor([12.])


In [45]:
# Example 2 of Autograd with multiple variable

a = torch.tensor(0.1, requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)
c = torch.tensor(0.1, requires_grad = True)
y=3*a + 2*b*b + torch.log(c)

y.backward()

print(a.grad) # tensor(3.)
print(b.grad) # tensor(4.)
print(c.grad) # tensor(10.)

tensor(3.)
tensor(4.)
tensor(10.)


### Neural Networks

So far we have looked into the tensors, their properties and basic operations on tensors. These are especially useful to get familiar with if we are building the layers of our network from scratch. We will utilize these in Assignment 3, but moving forward, we will use predefined blocks in the torch.nn module of PyTorch. We will then put together these blocks to create complex networks. Let's start by importing this module with an alias so that we don't have to type torch every time we use it.

In [46]:
import torch.nn as nn

#### Linear Layer

We can use nn.Linear(H_in, H_out) to create a a linear layer. This will take a matrix of (N, *, H_in) dimensions and output a matrix of (N, *, H_out). The * denotes that there could be arbitrary number of dimensions in between. The linear layer performs the operation Ax+b, where A and b are initialized randomly. If we don't want the linear layer to learn the bias parameters, we can initialize our layer with bias=False.

In [49]:
# Create the inputs 
input= torch.ones(2,3,4)

print(input)

# Make a linear layers transforming N,*,H_in dimensinal inputs to N,*,H_out
# dimensional outputs
linear = nn.Linear(4,2)
linear_output = linear(input)
linear_output

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[-0.6864, -0.1650],
         [-0.6864, -0.1650],
         [-0.6864, -0.1650]],

        [[-0.6864, -0.1650],
         [-0.6864, -0.1650],
         [-0.6864, -0.1650]]], grad_fn=<AddBackward0>)

#### Activation Functions
We can also use the nn module to apply activations functions to our tensors. Activation functions are used to add non-linearity to our network. Some examples of activations functions are nn.ReLU(), nn.Sigmoid() and nn.LeakyReLU(). Activation functions operate on each element seperately, so the shape of the tensors we get as an output are the same as the ones we pass in.

In [50]:
linear_output

tensor([[[-0.6864, -0.1650],
         [-0.6864, -0.1650],
         [-0.6864, -0.1650]],

        [[-0.6864, -0.1650],
         [-0.6864, -0.1650],
         [-0.6864, -0.1650]]], grad_fn=<AddBackward0>)

In [51]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)

output

tensor([[[0.3348, 0.4589],
         [0.3348, 0.4589],
         [0.3348, 0.4589]],

        [[0.3348, 0.4589],
         [0.3348, 0.4589],
         [0.3348, 0.4589]]], grad_fn=<SigmoidBackward0>)

#### Putting Layers together

So far we have seen that we can create layers and pass the output of one as the input of the next. Instead of creating intermediate tensors and passing them around, we can use nn.Sequentual, which does exactly that.

In [52]:
block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.4466, 0.4141],
         [0.4466, 0.4141],
         [0.4466, 0.4141]],

        [[0.4466, 0.4141],
         [0.4466, 0.4141],
         [0.4466, 0.4141]]], grad_fn=<SigmoidBackward0>)

#### Custom Modules
Instead of using the predefined modules, we can also build our own by extending the nn.Module class. For example, we can build a the nn.Linear (which also extends nn.Module) on our own using the tensor introduced earlier! We can also build new, more complex modules, such as a custom neural network. 

To create a custom module, the first thing we have to do is to extend the nn.Module. We can then initialize our parameters in the __init__ function, starting with a call to the __init__ function of the super class. All the class attributes we define which are nn module objects are treated as parameters, which can be learned during the training. Tensors are not parameters, but they can be turned into parameters if they are wrapped in nn.Parameter class.

All classes extending nn.Module are also expected to implement a forward(x) function, where x is a tensor. This is the function that is called when a parameter is passed to our module, such as in model(x).

In [67]:
class MultilayerPerceptron(nn.Module):
    
    def __init__(self, input_size, hidden_size):
        #Call the _init_ function of the super class nn.Module
        #this is called inheritence
        super(MultilayerPerceptron, self).__init__()
        
        #saving the initial parameters
        self.input_size = input_size
        self.hidden_size = hidden_size
        
        #defining our model
        # There isn't anything specific about the naming of `self.model`. It could
    # be something arbitrary.
        self.model = nn.Sequential(
            nn.Linear(self.input_size, self.hidden_size),
            nn.ReLU(),
            nn.Linear(self.hidden_size, self.input_size),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        output = self.model(x)
        return output

In [68]:
# Make a sample input
input =torch.randn(2,5)

#Create model

model = MultilayerPerceptron(5,3)

#Pass the input through our model
model(input)

tensor([[0.6246, 0.5524, 0.5314, 0.4767, 0.5616],
        [0.5474, 0.5172, 0.5384, 0.5579, 0.5687]], grad_fn=<SigmoidBackward0>)

In [69]:
# inspect parameters if the model
list(model.named_parameters())

[('model.0.weight',
  Parameter containing:
  tensor([[ 0.3185,  0.4021, -0.3229, -0.1167,  0.1969],
          [-0.1114, -0.1121,  0.1813,  0.1332,  0.4466],
          [ 0.1096, -0.4241, -0.3529,  0.1510, -0.1970]], requires_grad=True)),
 ('model.0.bias',
  Parameter containing:
  tensor([-0.3822,  0.3071, -0.0531], requires_grad=True)),
 ('model.2.weight',
  Parameter containing:
  tensor([[-0.1359,  0.2657, -0.2584],
          [-0.4570,  0.4134,  0.4487],
          [ 0.2326, -0.1005, -0.1244],
          [ 0.2399, -0.2688,  0.2695],
          [-0.2951,  0.1413,  0.3387]], requires_grad=True)),
 ('model.2.bias',
  Parameter containing:
  tensor([ 0.2798, -0.1463,  0.2126,  0.1385,  0.1257], requires_grad=True))]

#### Optimizer

We have showed how gradients are calculated with the backward() function. Having the gradients isn't enought for our models to learn. We also need to know how to update the parameters of our models. This is where the optimizers comes in. torch.optim module contains several optimizers that we can use. Some popular examples are optim.SGD and optim.Adam. When initializing optimizers, we pass our model parameters, which can be accessed with model.parameters(), telling the optimizers which values it will be optimizing. Optimizers also has a learning rate (lr) parameter, which determines how big of an update will be made in every step. Different optimizers have different hyperparameters as well.

In [71]:
import torch.optim as optim

After we have our optimization function, we can define a loss that we want to optimize for. We can either define the loss ourselves, or use one of the predefined loss function in PyTorch, such as nn.BCELoss(). Let's put everything together now! We will start by creating some dummy data.

In [72]:
# Create dummy data y
y = torch.ones(10,5)

#add some random noise
x = y + torch.randn_like(y)

x

tensor([[ 1.1410,  1.3278,  2.2789, -0.0587,  1.3465],
        [ 1.8383,  0.9794,  1.6132,  0.6001,  1.4271],
        [-0.0836,  2.0081,  1.5900,  1.3299,  3.1222],
        [ 0.2449,  3.3850,  0.6343,  1.6930,  1.1947],
        [ 2.7479, -0.1616,  2.4396,  0.4190,  1.0997],
        [ 0.6747,  0.8883,  0.2801,  2.0999,  0.9491],
        [-1.8206,  2.4538,  1.4040,  1.3073,  1.4065],
        [-0.4987,  1.3135,  1.9775,  1.8416,  2.3042],
        [-0.6039,  0.8761,  1.5620,  0.5114,  0.9238],
        [-0.1877,  1.2864,  2.6097,  1.3650,  1.2611]])

In [75]:
# Instantiating the model

model = MultilayerPerceptron(5, 3)

# Define the optimizer
adam = optim.Adam(model.parameters(), lr=1e-1)

#Define Loss using a predefined loss function
loss_function = nn.BCELoss()

# compute the model performance
y_pred = model(x)
loss_function(y_pred, y).item()

1.1675994396209717

#### Training the model

In [77]:
# set the number of iterations also called epochs
n_epoch = 10

for epoch in range(n_epoch):
    #set the gradients to zero
    adam.zero_grad()
    
    #Get the model predictions
    y_pred = model(x)
    
    # get the loss
    loss = loss_function(y_pred, y)
    
    #Print stats
    print(f"Epoch {epoch}: training loss: {loss}")
    
    #Compute the gradients
    loss.backward()
    
    #take a step to optimize the weights
    adam.step()

Epoch 0: training loss: 1.1675994396209717
Epoch 1: training loss: 0.8803694248199463
Epoch 2: training loss: 0.6795225739479065
Epoch 3: training loss: 0.5129404664039612
Epoch 4: training loss: 0.36155399680137634
Epoch 5: training loss: 0.23067373037338257
Epoch 6: training loss: 0.1320425570011139
Epoch 7: training loss: 0.06835171580314636
Epoch 8: training loss: 0.032941725105047226
Epoch 9: training loss: 0.015373587608337402


You can see that our loss is decreasing. Let's check the predictions of our model now and see if they are close to our original y, which was all 1s.

In [78]:
# See how our model performs on the training data
y_pred = model(x)
y_pred

tensor([[0.9861, 0.9996, 0.9970, 0.9998, 0.9943],
        [0.9899, 0.9998, 0.9981, 0.9999, 0.9962],
        [0.9945, 0.9999, 0.9992, 1.0000, 0.9982],
        [0.9908, 0.9998, 0.9983, 0.9999, 0.9966],
        [0.9918, 0.9999, 0.9986, 0.9999, 0.9971],
        [0.9764, 0.9989, 0.9939, 0.9995, 0.9890],
        [0.9648, 0.9977, 0.9893, 0.9987, 0.9818],
        [0.9910, 0.9998, 0.9984, 0.9999, 0.9967],
        [0.9374, 0.9928, 0.9761, 0.9955, 0.9623],
        [0.9877, 0.9997, 0.9975, 0.9999, 0.9952]], grad_fn=<SigmoidBackward0>)

In [79]:
# create test data and check the model performance

x2 = y + torch.randn_like(y)
y_pred = model(x2)
y_pred

tensor([[0.9808, 0.9993, 0.9954, 0.9996, 0.9915],
        [0.9870, 0.9997, 0.9973, 0.9998, 0.9948],
        [0.9781, 0.9991, 0.9945, 0.9995, 0.9900],
        [0.9638, 0.9975, 0.9889, 0.9986, 0.9812],
        [0.9605, 0.9971, 0.9875, 0.9984, 0.9790],
        [0.9438, 0.9942, 0.9795, 0.9965, 0.9672],
        [0.9876, 0.9997, 0.9975, 0.9999, 0.9951],
        [0.9967, 1.0000, 0.9996, 1.0000, 0.9990],
        [0.9830, 0.9994, 0.9961, 0.9997, 0.9927],
        [0.9504, 0.9954, 0.9828, 0.9973, 0.9720]], grad_fn=<SigmoidBackward0>)

In [ ]:
Congratulations you have finished this tutora